GET http://localhost:10350/version

###
GET http://localhost:10350/guests

###
GET http://localhost:10350/guests/AW0123456

###
DELETE http://localhost:10350/guests/AW0123456

###
POST http://localhost:10350/guests HTTP/1.1
content-type: application/json

{
  "bnmID": "AW0123456",
  "residency": "commuter",
  "grad_year": 2023,
  "grad": "UG",
  "date": "04-12-2023",
  "year_issued": 2022
}

###
POST http://localhost:10350/guests HTTP/1.1
content-type: application/json

{
  "bnmID": "AW7890123",
  "residency": "resident",
  "grad_year": 2024,
  "grad": "UG",
  "date": "04-15-2023",
  "year_issued": 2022
}

###
PUT http://localhost:10350/guests/AW7890123 HTTP/1.1
content-type: application/json

{
  "bnmID": "AW7890123",
  "residency": "resident",
  "grad_year": 2024,
  "grad": "G",
  "date": "04-15-2023",
  "year_issued": 2022
}

###
GET http://localhost:10350/visits

###
GET http://localhost:10350/visits/04-15-2023+04-26-2023

###
POST http://localhost:10350/visits HTTP/1.1
content-type: application/json

{
  "bnmID": "AW0123456",
  "date": "04-14-2023"
}

###
POST http://localhost:10350/visits HTTP/1.1
content-type: application/json

{
  "bnmID": "AW7890123",
  "date": "04-26-2023"
}
